const jobs = {
  data: [
    {
      id: 1,
      title: "Frontend Developer Needed",
      company: "Tedbree",
      company_logo:
        "https://content.app-sources.com/s/14630223212260103/uploads/Logos/Tedbree-5151946.png",
      location: "Lagos",
      category: "Tech",
      salary: "N150,000 per Month",
      description: "Description Frontend Developer Needed",
      benefits: "Free Meal",
      type: "Permanent",
      work_condition: "Remote",
    },
    {
      id: 2,
      title: "Backend",
      company: "Tedbree",
      company_logo:
        "https://content.app-sources.com/s/14630223212260103/uploads/Logos/Tedbree-5151946.png",
      location: "New york",
      category: "Tech",
      salary: "2000000",
      description: "uuuuuuu",
      benefits: "Free Meal",
      type: "Temporary",
      work_condition: "Part Remote",
    },
    {
      id: 3,
      title: "Backend Engineer",
      company: "Tedbree",
      company_logo:
        "https://content.app-sources.com/s/14630223212260103/uploads/Logos/Tedbree-5151946.png",
      location: "ssss",
      category: "Tech",
      salary: "2000000",
      description: "sssss",
      benefits: "Free Meal",
      type: "Temporary",
      work_condition: "Part Remote",
    },
    {
      id: 4,
      title: "Devops Engineer",
      company: "Tedbree",
      company_logo:
        "https://content.app-sources.com/s/14630223212260103/uploads/Logos/Tedbree-5151946.png",
      location: "Delta",
      category: "Tech",
      salary: "900000",
      description: "aaaaaa",
      benefits: "Free Meal",
      type: "Temporary",
      work_condition: "Part Remote",
    },
    {
      id: 5,
      title: "Devops",
      company: "Tedbree",
      company_logo:
        "https://content.app-sources.com/s/14630223212260103/uploads/Logos/Tedbree-5151946.png",
      location: "Delta",
      category: "Tech",
      salary: "900000",
      description: "aaaaaa",
      benefits: "Free Meal",
      type: "Temporary",
      work_condition: "Part Remote",
    },
    {
      id: 6,
      title: "QA",
      company: "Tedbree",
      company_logo:
        "https://content.app-sources.com/s/14630223212260103/uploads/Logos/Tedbree-5151946.png",
      location: "Abuja",
      category: "Tech",
      salary: "200000",
      description: "aaaaaaaa",
      benefits: "Free Meal",
      type: "Contract",
      work_condition: "Part Remote",
    },
    {
      id: 7,
      title: "wdwd",
      company: "jj",
      company_logo:
        "https://content.app-sources.com/s/14630223212260103/uploads/Logos/Tedbree-5151946.png",
      location: "wddw",
      category: "Tech",
      salary: "ww",
      description: "wdw",
      benefits: "Free Meal",
      type: "Internship",
      work_condition: "Part Remote",
    },
  ],
};
export default jobs;
